order.create=API to create a new order.
order.getById=API to get order details by order ID.
order.getAll=API to get all available orders.
order.update=API to update order details by order ID.
order.delete=API to delete an order by order ID.